[project]
name = "compilador"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ply (>=3.11,<4.0)"
]

[tool.poetry]
packages = [{include = "compilador", from = "src"}]

[tool.poetry.scripts]
compilador = "compilador.main:main"
test = "tests.runner:test"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
